using AuthVault.Installer.UI;

namespace AuthVault.Installer.Services;

public record AppConfig(
    int HttpsPort,
    int HttpPort,
    string DbPassword,
    string EmailHost,
    int EmailPort,
    string EmailUser,
    string EmailPassword,
    string EmailFrom);

public class ConfigurationService
{
    const string AppImage = "ghcr.io/blackcat-404/authvault:latest";

    // Interactive prompts

    public AppConfig PromptConfiguration()
    {
        Display.Section("Configuration");
        Display.Info("Press [bold]Enter[/] to accept defaults shown in brackets.\n");

        int httpsPort = Display.AskInt("HTTPS port", 7108);
        int httpPort = Display.AskInt("HTTP port", 5168);
        var dbPassword = PromptDbPassword();
        var emailHost = Display.Ask("SMTP host", "smtp.gmail.com");
        int emailPort = Display.AskInt("SMTP port", 587);
        var emailUser = Display.Ask("SMTP username (your email)");
        var emailPass = Display.AskSecret("SMTP password / app-password");
        var emailFrom = Display.Ask("From address shown in emails", emailUser);

        return new AppConfig(httpsPort, httpPort, dbPassword,
            emailHost, emailPort, emailUser, emailPass, emailFrom);
    }

    // Write ~/.authvault/.env

    public void WriteEnvFile(AppConfig cfg)
    {
        var connStr = $"Host=authvault-db;Port=5432;Database=authvaultdb;" +
                      $"Username=authvault;Password={cfg.DbPassword}";

        var lines = new[]
        {
            "# AuthVault configuration — generated by installer",
            "",
            $"HTTPS_PORT={cfg.HttpsPort}",
            $"HTTP_PORT={cfg.HttpPort}",
            $"DB_PASSWORD={Quote(cfg.DbPassword)}",
            "",
            "# ASP.NET Core environment variable overrides",
            $"ConnectionStrings__DefaultConnection={Quote(connStr)}",
            $"EmailSettings__Host={cfg.EmailHost}",
            $"EmailSettings__Port={cfg.EmailPort}",
            $"EmailSettings__Username={cfg.EmailUser}",
            $"EmailSettings__Password={Quote(cfg.EmailPassword)}",
            $"EmailSettings__From={Quote($"AuthVault <{cfg.EmailFrom}>")}",
            $"Kestrel__Endpoints__Http__Url=http://+:{cfg.HttpPort}",
            $"Kestrel__Endpoints__Https__Url=https://+:{cfg.HttpsPort}",
            "Kestrel__Endpoints__Https__Certificate__Path=/app/certs/localhost.pfx",
            "Kestrel__Endpoints__Https__Certificate__Password=",
        };

        File.WriteAllLines(InstallPaths.EnvFile, lines);
        Display.Success(".env written");
    }

    // Write ~/.authvault/docker-compose.yml

    public void WriteComposeFile(AppConfig cfg)
    {
        var content = string.Format("""
            services:
              authvault-app:
                image: {0}
                container_name: authvault-app
                env_file: .env
                volumes:
                  - ./certs:/app/certs:ro
                ports:
                  - "${{HTTPS_PORT}}:${{HTTPS_PORT}}"
                  - "${{HTTP_PORT}}:${{HTTP_PORT}}"
                dns:
                  - 8.8.8.8
                  - 8.8.4.4
                depends_on:
                  authvault-db:
                    condition: service_healthy
                restart: unless-stopped
                networks:
                  - authvault-net

              authvault-db:
                image: postgres:16-alpine
                container_name: authvault-db
                environment:
                  POSTGRES_DB: authvaultdb
                  POSTGRES_USER: authvault
                  POSTGRES_PASSWORD: "${{DB_PASSWORD}}"
                volumes:
                  - authvault-data:/var/lib/postgresql/data
                healthcheck:
                  test: ["CMD-SHELL", "pg_isready -U authvault -d authvaultdb"]
                  interval: 5s
                  timeout: 5s
                  retries: 10
                  start_period: 10s
                restart: unless-stopped
                networks:
                  - authvault-net

            volumes:
              authvault-data:
                name: authvault-data

            networks:
              authvault-net:
                driver: bridge
            """, AppImage);

        File.WriteAllText(InstallPaths.ComposeFile, content);
        Display.Success("docker-compose.yml written");
    }

    // Helpers

    string PromptDbPassword()
    {
        while (true)
        {
            var pass = Display.AskSecret("PostgreSQL password (min 8 characters)");
            var confirm = Display.AskSecret("Confirm password");

            if (pass != confirm)
            {
                Display.Error("Passwords do not match. Try again.");
                continue;
            }

            if (pass.Length < 8)
            {
                Display.Error("Password must be at least 8 characters.");
                continue;
            }

            return pass;
        }
    }

    static string Quote(string value) => $"\"{value.Replace("\"", "\\\"")}\"";
}
